# Generated by Django 5.0.1 on 2024-03-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='diretor',
            new_name='director',
        ),
    ]
